version: '2'

services:

  postgres:
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/databases
    networks:
      - mqtt
    ports:
      - "15432:5432"
    ## Disabled volumes because of https://github.com/docker/for-win/issues/39
    #volumes:
    #  - ./docker-data/mqtt-stuff/postgresql/data:/var/lib/postgresql/data

  postgres-provisioning:
    networks:
      - mqtt
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mqtt

  mqtt-master:
    restart: unless-stopped
    networks:
      - mqtt
    environment:
      - POSTGRES=true
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mqtt
      - EMQ_LOADED_PLUGINS=emq_auth_pgsql,emq_recon,emq_modules,emq_retainer,emq_dashboard
      - EMQ_LOG__CONSOLE__LEVEL=debug
      - EMQ_LOG__SYSLOG__LEVEL=debug
      - EMQ_MQTT__ALLOW_ANONYMOUS=false
      - EMQ_ACL_NOMATCH=deny
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8883:8883"
      - "18083:18083"
    volumes:
      - ./docker-data/mqtt-stuff/emqttd/log:/opt/emqttd/log

  node-red:
    restart: unless-stopped
    networks:
      - mqtt
    ports:
      - "11880:1880"
    volumes:
      - ./docker-data/mqtt-stuff/node-red/data:/data
