version: '2'

#networks:
#  logging:
#    driver: bridge

services:
  elasticsearch:
    restart: unless-stopped
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - logging
    volumes:
      - ./docker-data/elk-stuff/elasticsearch/:/opt/elasticsearch/data

  kibana:
    restart: unless-stopped
    ports:
      - "13501:80"
    networks:
      - logging
    environment:
      - LOGSPOUT=ignore