version: '2'

services:
  postgres:
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/databases
    networks:
      - mqtt
    ports:
      - "5432:5432"
    volumes:
    - /docker-data/mqtt-stuff/postgresql/data:/var/lib/postgresql/data

  #postgres-provisioning:
  #  networks:
  #    - mqtt
  #  environment:
  #    - POSTGRES_USER=postgres
  #    - POSTGRES_PASSWORD=postgres
  #    - POSTGRES_DB=mqtt

  mqtt-master:
    restart: unless-stopped
    networks:
      - mqtt
    environment:
      - POSTGRES=true
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mqtt
      - EMQ_LOADED_PLUGINS=emq_recon,emq_modules,emq_retainer,emq_dashboard
      - EMQ_LOG__CONSOLE__LEVEL=debug
      - EMQ_LOG__SYSLOG__LEVEL=debug
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8883:8883"
      - "18083:18083"
    volumes:
      - ./docker-data/mqtt-stuff/emqttd/log:/opt/emqtt/log
